### ISSUE TITLE
Typos in patches

### ISSUE THREAD

**Issue by szepeviktor** [cyberus-technology/virtualbox-kvm#32]
### Bug Description

Found few misspellings.

### How to Reproduce

https://github.com/szepeviktor/typos-on-you/actions/runs/10023968701/job/27705459930

Would you welcome a PR?
Or a configuration file for https://github.com/crate-ci/typos ?

**Comment by szepeviktor** [comment]
> Or a configuration file

`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "index [0-9a-f]{10}\\.\\.[0-9a-f]{10}",
]

[default.extend-identifiers]
"BARs" = "BARs"
"PDMAPICIRQ_EXTINT" = "PDMAPICIRQ_EXTINT"
```
